version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - run:
          name: Install dependencies
          command: |
            set -ex

            curl -L 'https://www.archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4&use_mirror_status=on' | \
              sed 's/#Server/Server/' > /etc/pacman.d/mirrorlist
            echo 'root ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
            echo 'nobody ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
            echo 'Defaults env_keep += "PATH"' >> /etc/sudoers

            export PATH="$PATH:/usr/bin/core_perl"
            pacman -Sy confuse expac fontconfig freetype2 git libxkbcommon mesa perl yajl --noconfirm --needed

            curl -o PKGBUILD.cower https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=cower
            sudo -u nobody sh -c "cd ~; makepkg $HOME/PKGBUILD.cower --skippgpcheck --install --needed"
            curl -o PKGBUILD.pacaur https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur
            sudo -u nobody sh -c "cd ~; makepkg $HOME/PKGBUILD.pacaur --skippgpcheck --install --needed"

            sudo -u nobody pacaur -S glfw-x11-git --noconfirm --noconfirm --noedit --needed
      - checkout:
          post:
            - git submodule sync
            - git submodule update --init
      - run:
          name: Install fbuild
          command: |
            git clone https://github.com/felix-lang/fbuild.git
            cd fbuild
            python setup.py install
      - run:
          name: Build uterm
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
