version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - run:
          name: Install dependencies
          command: |
            set -ex

            curl -L 'https://www.archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4&use_mirror_status=on' | \
              sed 's/#Server/Server/' > /etc/pacman.d/mirrorlist
            echo 'root ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
            echo 'nobody ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
            echo 'Defaults env_keep += "PATH"' >> /etc/sudoers

            export PATH="$PATH:/usr/bin/core_perl"
            # XXX
            mkdir /.cache
            chown -R nobody /.cache

            pacman -Sy clang confuse expac fontconfig freetype2 git libxkbcommon lld mesa perl python python-setuptools yajl \
              --noconfirm --needed

            sudo -u nobody sh -c '
              cd /tmp
              curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=cower
              makepkg PKGBUILD --skippgpcheck --install --needed --noconfirm
              curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur
              makepkg PKGBUILD --skippgpcheck --install --needed --noconfirm
            '

            sudo -u nobody pacaur -S glfw-x11-git upspin-git --noconfirm --noconfirm --noedit --needed
      - run:
          name: Checkout uterm (with submodules)
          command: |
            git clone --recursive https://github.com/kirbyfan64/uterm.git
      - run:
          name: Install fbuild
          command: |
            git clone https://github.com/felix-lang/fbuild.git
            cd fbuild
            python setup.py install
      - run:
          name: Build uterm
          command: |
            cd uterm
            fbuild --release -j4
