version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - run:
          name: Install dependencies
          command: |
            set -ex
            curl -L 'https://www.archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4&use_mirror_status=on' | \
              sed 's/#Server/Server/' > /etc/pacman.d/mirrorlist
            echo 'root ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
            echo 'nobody ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
            echo 'Defaults env_keep += "PATH"' >> /etc/sudoers
            export PATH="$PATH:/usr/bin/core_perl"
            pacman -Sy confuse fontconfig freetype2 git libxkbcommon mesa perl --noconfirm --needed
            # https://gist.github.com/Tadly/0e65d30f279a34c33e9b: install Pacaur
            curl -Ls https://goo.gl/cF2iJy | sed '/sudo pacman -Syu/d' | sudo -u nobody bash
            sudo -u nobody pacaur -S glfw-x11-git --noconfirm --noconfirm --noedit --needed
      - checkout:
          post:
            - git submodule sync
            - git submodule update --init
      - run:
          name: Install fbuild
          command: |
            git clone https://github.com/felix-lang/fbuild.git
            cd fbuild
            python setup.py install
      - run:
          name: Build uterm
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
